name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --all-features
    - name: Run formatter
      run: |
        rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
        cargo +nightly fmt
